# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to=projects.models.upload_project_img)),
                ('link', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goal', to='projects.Project')),
            ],
        ),
    ]
