# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
