# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180525_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(default='wef', upload_to=projects.models.upload_project_img),
            preserve_default=False,
        ),
    ]
